/** 首批组件名（kebab-case），与按需入口文件、样式产物一一对应 */
export const componentNames = [
  'action-sheet',
  'activity-indicator',
  'agree',
  'amount',
  'button',
  'cell-item',
  'check',
  'check-base',
  'codebox',
  'date-picker',
  'dialog',
  'field',
  'field-item',
  'icon',
  'input-item',
  'notice-bar',
  'number-keyboard',
  'picker',
  'popup',
  'progress',
  'radio',
  'radio-list',
  'skeleton',
  'stepper',
  'switch',
  'tag',
  'tip',
  'toast',
] as const

export type ComponentName = (typeof componentNames)[number]
